# Johdanto


Korrespondenssianalyysi on deskriptiivinen data-analyysin menetelmä, joka
soveltuu erityisesti luokitteluasteikon muuttujien yhteyksien analyysiin.
Yksinkertainen esimerkki on kahden luokittelumuuttuja taulukko. Yksinkertainen
korrespondenssianalyysi esittää taulukon rivien ja sarakkeiden riippuvuuden
graafisesti, kaksiulotteisena karttana. Kahden muuttujan analyysin perusideat
soveltuvat myös useamman muuttujan yhteyksien kuvaamiseen.

Taulukoita on kaikkialla, mutta niiden graafinen analyysi ei ole kovin yleistä.


## Tutkielman tavoite ja toteutus


Tämän tutkielman tavoite on esittää korrespondenssianalyysin periaatteet
data-analyysin sovellusten avulla. Tutustuin aiheeseen Michael Greenacren
luennoilla Helsingissä keväällä 2017.
Aivan huomaamatta tein harjoitustehtävinä karttoja, joita en oikein ymmärtänyt.


Pyrin esittelemään menetelmän niin, että data-analyysistä kiinnostunut lukija
oivaltaa karttojen tulkinnan perusperiaatteet. Tilastotieteessä on aina ollut
osana käytännöllinen, soveltajille suunnattu menetelmien esittely. En kirjoita
kuitenkaan oppikirjaa, vaan tutkielman, jossa esittelen aineiston analyysin
avulla menetelmää. Analyysien r-koodi on vapaasti saatavilla verkossa, kuten
tämän tutkielman käsikirjoitus.


En etsi datasta vastauksia joihinkin substanssikysymyksiin vaan havainnollistan
menetelmän mahdollisuuksia datan analyysissä. Tavoitteena on myös oman
ymmärryksen lisääminen.


Tutkielman toteutus on rakennettu kolmelle perusajatukselle.


Yksinkertainen kahden luokittelumuuttujan korrespondenssianalyysi antaa graafisen
analyysin ”...perussäännöt tulkinnalle. Kaikki muut korrespondenssianalyysin
muodot ovat saman algoritmin soveltamista toisen tyyppisiin datamatriiseihin,
ja tulkintaa sovelletaan vastaavasti (with the consequent adaptation of the
interpretation)”(@RefWorks:doc:5a857a44e4b0ed2d44664d84 s. 437).


Tutkielma laajin osa on yksinkertaisen korrespondenssianalyysin tulosten ja
peruskäsitteiden esittelyä.


Toiseksi käytän laajaa ja laadukasta kansainvälisen haastattelututkimuksen aineistoa.
Korrespondenssianalyysi sopii survey-aineistojen analyysiin mainiosti, ja samaa
dataa on käytetty alan oppikirjoissa ja artikkeleissa esimerkkiaineistona.
Laaja ja mutkikas aineisto antaa oikean kuvan data-analyysistä ja samalla ohjaa
analyysin kulkua. Data yllättää aina. Menetelmän on taivuttava tarvittaessa
uusiin suuntiin. Tutkielman data-analyysissä jouduin moneen kertaan miettimään
mihin suuntaan kannattaisi edetä. Datan analyysi tuo esiin jotain sen
ominaisuuksia, vaikka mitään sisällöllistä tutkimusongelmaa ei ole määritelty.


Kolmanneksi keskityn graafiseen analyysiin, kuvien tulkintaan.
Korrespondenssianalyysin idea on esittää mutkikkaat riippuvuudet ja yhteydet
kuvana. Samalla tavoite on tiivistää moniulotteisen datan informaatiosta
mahdollisimman paljon kaksiulotteiselle kartalle. Informaatiota menetetään,
ja tulkinnan varmistaminen numeerisista tuloksista estää virhepäätelmät. Kartan
lukeminen ei ole aivan helppoa, mutta perussäännöt ovat melko selkeät.
Graafinen data-analyysi on tasapainoilua datan analyysin ja tulosten esittämisen
välillä. Tässä painottuu data-analyysi, ei vaativa viimeisteltyjen
graafisten esitysten suunnittelu ja toteutus. Graafinen data-analyysi
ei aina ole helppoa ja nopeaa.


## Korrespondenssianalyysin historiaa


Korrespondenssianalyysi on 80-luvun alusta vähitellen vakiinnuttanut asemansa
yhtenä ei-parametrisen kuvailevan data-analyysin menetelmänä. Kansainvälinen
tutkijaverkosto CARME (Correspondence analysis and related methods network)
järjesti ensimmäisen konferenssin 1991 ( http://www.carme-n.org ).


Korrespondenssianalyysi esitellään oppikirjoissa muiden menetelmien rinnalla.
MG (ecological data)[@RefWorks:doc:5b8175eee4b08da192f99a35], kaksoisikuvat ja
compositional data [@RefWorks:doc:5f934955e4b08d20366a5bd1]. Suomessa
korrespondenssianalyysi esitellään kahdessa oppikirjassa
(@RefWorks:doc:5a857a44e4b0ed2d44664d95 , @RefWorks:doc:5a857a44e4b0ed2d44664da4).


Korrespondenssianalyysi ja koulukunta syntyi ja vakiintui Ranskassa Jean - Paul Benzecrin
(1932-2019) ympärille 60-luvulla.  70-luku oli “loistavan eristyksen” aikaa,
“Analyse des Donnees” -liikkeen kultainen kausi Ranskassa mutta ei muualla.
Vasta 80-luvulla menetelmä ylitti kielimuurin, ehkä osittain menetelmää
soveltaneen sosiologi Pierre Bourdieun kansainvälisesti tunnettujen tutkimusten
ansiosta. Benzecrin oppilaista Greenacre on oppikirjoillaan vaikuttanut paljon
menetelmän vakiinnuttamiseen osaksi tilastotieteen perustekniikoita.Hänen
oppikirjojensa nimet eivät turhaa pääty "...in practice".

Toisena muurina on pidetty ranskalaisen koulukunnan tiukkaa “bourbakilaista”
matemaattista esitystapaa.@RefWorks:doc:5a857a43e4b0ed2d44664d75 esittelee tämän
lähestymistavan englanniksi. Lyhyt historiallinen katsaus
ja menetelmä soveltamisen perusajatusten esittely
valaisevat ranskaa taitamattomalle data-analyysin koulukunnan ideoita.
Kirjassa esitellään myös hyvin perusteellisesti muutama empiirinen tutkimus.


Tarina on kiinnostava ja tärkeäkin osa tieteenhistoriaa, mutta eristys on päättynyt. 

## Tutkielman rakenne


Datan kuvailun jälkeen CA:n peruskäsitteet esitellään yksikertaisen esimerkin
avulla luvussa 3. 


Luvuissa 4 - 5 analyysiin lisätään täydentäviä pisteitä tulkinnan tueksi
ja muodostetaan luokittelumuuttujien yhteisvaikutusmuuttujia (ikä ja sukupuoli).


Kolmen muuttujan yhteisvaikutusmuuttujan (maa, sukupuoli ja ikäluokka) analyysi
tehdään osajoukon korrespondenssianalyysillä luvussa 6.


Luvussa 7 esitellään lyhyesti kaksi tapaa tutkia useamman muuttujan yhteyksiä.
Taulukoita yhdistämällä voidaan analysoida kahden muuttujaryhmän välisiä yhteyksiä.
Monimuuttujakorrespondenssianalyysia sovelletaan isoon aineistoon ja tällaisten
aineistojen yleiseen ongelmaan, puuttuviin tietoihin.

 
Luvussa 8 kerrotaan, mistä alettiin ja mitä tuloksia saatiin.


Tutkielmassa on kolme liitettä.


Liite 1 esittelee tiiviisti menetelmän teorian.
Korrespondenssianalyysin numeerisia tuloksia havainnollistetaan kuvalla, ja
monimuuttujakorrespondenssianalyysin (MCA) käsitteitä esitellään hieman enemmän.
MCA:n teoriaa ei laajemmin esitellä, mutta tulkinnan ongelmia esitellään lyhyesti.

Tutkielma on tehty R-tilastohjelmalla, ja korrespondenssianalyyseissä on käytetty
ca-pakettia( @ca2007 ).  

Tutkielman koodi on julkaistu Github-palvelussa (https://github.com/hirjus/capaper),
samoin tutkielman käsikirjoitus ( https://hirjus.github.io/capaper/  )
ja alustava data-analyysi.

Tekninen ympäristö on kuvattu tarkemmin liitteessä 2., myös sen ongelmat.

Liitteessä 3 on listattu tutkielman R-koodi.

## Tärkeimmät lähteet

Tutkielman tärkein lähde on [@RefWorks:doc:5a857a43e4b0ed2d44664d78] (jatkossa CAiP),
ja muitakin saman tekijän artikkeleita on käytetty paljon. Kevään 2017
kurssimateriaali[@RefWorks:doc:5b6ef091e4b0984fd9b8c0ca] ja laskuharjoitusten koodi
on ollut hyödyllinen pikaopas peruskäsitteisiin ja r-toteutuksen ratkaisuihin.

@RefWorks:doc:5ab76b43e4b003f4468d1f07 toimittama Carme-verkoston kolmas
artikkelikokoelma  on ajantasainen perusteos.Perusteelliset artikkelit kattavat
myös korrespondenssianalyysin tärkeimmät aiheet.



Data on ensin luettava ohjelman ymmärtämään muotoon, ja erilaiset muunnokset kannattaa
tehdä heti kun data luetaan. @RefWorks:doc:5c3759c2e4b0085b307c82b5 kertovat,
miten luokittelumuuttujia pitää R-koodissa käsitellä.