# Yhteenveto

Jäsennysdokumentissa on muutama ajatus, ja viite. Kirjoitetaan tämä viimeiseksi.

**k** Onko maiden vertailu järkevää?
Blasius ja Thiessen
"This paper provides empirically-based criteria for selecting Items and countries
to develop measures of an underlying construct of interest that are comparable in
cross-national research. Using data from the 1994 International Social Survey
Program and applying multiple correspondence analysis to a set of common items
in each of the 24 participating countries, we show that both the quality of the
data, as well as its underlying structure - and therefore meaning - vary
considerably between countries. The approach we use for screening countries and
items is especially useful in situations where the psychometric properties of
the items have not been well established in previous research."
[@RefWorks:doc:5b15542ee4b0e2616bc42dca]

**k** voiko järjestysasteikon muuttujilla tehdä vertailuja maiden välillä?

"Surullinen totuus onnellisuustutkimuksesta" @RefWorks:doc:5c223412e4b0508a6674dec0 
(ilman sulkuja) ja suluilla [@RefWorks:doc:5c223412e4b0508a6674dec0]

**k** Eksploratiivinen data-analyysi ja todennäköisyysteoreettinen päättely

Gifi-nimimerkillä kirjoittavat Jan De Leeuw jatkavat verkkokirjassaan 
[@RefWorks:doc:5faaf996e4b05416e98ff547] keskustelua konfirmatorisen ja
data-analyyttisen eksploratiivisen lähestymistavan eroista. He ovat tiukasti
eksploratiivisen linjan kannattajia, ja korostavat konfliktin pitkää historiaa.
Nyt historia on heidän mielestään loppunut: "We shall not pay much attention any
more to these turf and culture wars, because basically they are over. Data
analysis, in its multitude of disguises and appearances, is the winner.
Classical statistics departments are gone, or on their way out. They may not
have changed their name, but their curricula and hiring practices are very
different from what they were 20 or even 10 years ago."

**k** Miksi ei molempia? 

**k1** Visualisointi on tehokasta tapa tutkia aineiston rakenetta, yhteyksiä
muuttujien välillä ja eri havaintojoukkojen eroja. Ei automaattisesti helppoa, 
mutta kahden luokitelumuuttujan taulukko on ehkä yleisin tapa esittää mitä
tahansa dataa. CA on aika pätevä väline taulukon riippuvuuksien hahmottamiseen
yhdellä kartalla.

**k2** Jo oppikirjoista näkee, että tarvitaan monta menetelmää ja näkökulmaa.
"jack of all trades but master of none", sellainen on data-analyytikko.

**k21*' MCA-esimerkki, eikö ole mainio lähtökohta faktorianalyysille?

**k** Tulevaisuus?

"The applicability of a dimension-reduction technique on very large categorical
data sets or on categorical data streams is limited due to the required singular
value decomposition (SVD) of properly transformed data. The application of SVD
to large and high-dimensional data is unfeasible because of the very large
computational time and because it requires the whole data to be stored in memory
(no data flows can be analysed). The aim of the present paper is to integrate an
incremental SVD procedure in a multiple correspondence analysis (MCA)-like
procedure in order to obtain a dimensionality reduction technique feasible for
the application on very large categorical data or even on categorical
data streams"[@RefWorks:doc:5f01c74be4b0d3d8328c72ca].