<!DOCTYPE html>
<html lang="fi" xml:lang="fi">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Luku 6 Osajoukon korrespondenssianalyysi | Korrespondenssianalyysi - graafinen ja geometrinen data-analyysin menetelmä</title>
  <meta name="description" content="Tutkielma korrespondenssianalyysistä graafisena data-analyysin menetelmänä." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Luku 6 Osajoukon korrespondenssianalyysi | Korrespondenssianalyysi - graafinen ja geometrinen data-analyysin menetelmä" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Tutkielma korrespondenssianalyysistä graafisena data-analyysin menetelmänä." />
  <meta name="github-repo" content="hirjus/capaper" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Luku 6 Osajoukon korrespondenssianalyysi | Korrespondenssianalyysi - graafinen ja geometrinen data-analyysin menetelmä" />
  
  <meta name="twitter:description" content="Tutkielma korrespondenssianalyysistä graafisena data-analyysin menetelmänä." />
  

<meta name="author" content="Jussi Hirvonen" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="yhteisvaikutusmuuttujat.html"/>
<link rel="next" href="monimuuttuja-korrespondenssianalyysi-mca.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Alkutoimia</a></li>
<li class="chapter" data-level="1" data-path="johdanto.html"><a href="johdanto.html"><i class="fa fa-check"></i><b>1</b> Johdanto</a><ul>
<li class="chapter" data-level="1.1" data-path="johdanto.html"><a href="johdanto.html#tutkielman-tavoite"><i class="fa fa-check"></i><b>1.1</b> Tutkielman tavoite</a></li>
<li class="chapter" data-level="1.2" data-path="johdanto.html"><a href="johdanto.html#tärkeimmät-lähteet-ja-ohjelmistot"><i class="fa fa-check"></i><b>1.2</b> Tärkeimmät lähteet ja ohjelmistot</a></li>
<li class="chapter" data-level="1.3" data-path="johdanto.html"><a href="johdanto.html#korrespondenssianalyysin-historiaa"><i class="fa fa-check"></i><b>1.3</b> Korrespondenssianalyysin historiaa</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>2</b> Data</a><ul>
<li class="chapter" data-level="2.1" data-path="data.html"><a href="data.html#aineiston-rajaaminen-maat-ja-muuttujat"><i class="fa fa-check"></i><b>2.1</b> Aineiston rajaaminen maat ja muuttujat</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="yksinkertainen-korrespondenssianalyysi.html"><a href="yksinkertainen-korrespondenssianalyysi.html"><i class="fa fa-check"></i><b>3</b> Yksinkertainen korrespondenssianalyysi</a><ul>
<li class="chapter" data-level="3.1" data-path="yksinkertainen-korrespondenssianalyysi.html"><a href="yksinkertainen-korrespondenssianalyysi.html#äiti-töissä---kärsiikö-lapsi"><i class="fa fa-check"></i><b>3.1</b> Äiti töissä - kärsiikö lapsi?</a></li>
<li class="chapter" data-level="3.2" data-path="yksinkertainen-korrespondenssianalyysi.html"><a href="yksinkertainen-korrespondenssianalyysi.html#symmetrinen-kartta"><i class="fa fa-check"></i><b>3.2</b> Symmetrinen kartta</a></li>
<li class="chapter" data-level="3.3" data-path="yksinkertainen-korrespondenssianalyysi.html"><a href="yksinkertainen-korrespondenssianalyysi.html#korrespondenssianalyysin-peruskäsitteet"><i class="fa fa-check"></i><b>3.3</b> Korrespondenssianalyysin peruskäsitteet</a><ul>
<li class="chapter" data-level="3.3.1" data-path="yksinkertainen-korrespondenssianalyysi.html"><a href="yksinkertainen-korrespondenssianalyysi.html#asymmetrinen-kartta-ja-ideaalipisteet"><i class="fa fa-check"></i><b>3.3.1</b> Asymmetrinen kartta ja ideaalipisteet</a></li>
<li class="chapter" data-level="3.3.2" data-path="yksinkertainen-korrespondenssianalyysi.html"><a href="yksinkertainen-korrespondenssianalyysi.html#barysentrinen-periaate"><i class="fa fa-check"></i><b>3.3.2</b> Barysentrinen periaate</a></li>
<li class="chapter" data-level="3.3.3" data-path="yksinkertainen-korrespondenssianalyysi.html"><a href="yksinkertainen-korrespondenssianalyysi.html#kontribuutiot-kartalla"><i class="fa fa-check"></i><b>3.3.3</b> Kontribuutiot kartalla</a></li>
<li class="chapter" data-level="3.3.4" data-path="yksinkertainen-korrespondenssianalyysi.html"><a href="yksinkertainen-korrespondenssianalyysi.html#massat"><i class="fa fa-check"></i><b>3.3.4</b> Massat</a></li>
<li class="chapter" data-level="3.3.5" data-path="yksinkertainen-korrespondenssianalyysi.html"><a href="yksinkertainen-korrespondenssianalyysi.html#karttojen-erot"><i class="fa fa-check"></i><b>3.3.5</b> Karttojen erot</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="täydentävät-pisteet.html"><a href="täydentävät-pisteet.html"><i class="fa fa-check"></i><b>4</b> Täydentävät pisteet</a><ul>
<li class="chapter" data-level="4.1" data-path="täydentävät-pisteet.html"><a href="täydentävät-pisteet.html#saksan-ja-belgian-alueet"><i class="fa fa-check"></i><b>4.1</b> Saksan ja Belgian alueet</a></li>
<li class="chapter" data-level="4.2" data-path="täydentävät-pisteet.html"><a href="täydentävät-pisteet.html#korrespondenssianalyysin-numeeriset-tulokset"><i class="fa fa-check"></i><b>4.2</b> Korrespondenssianalyysin numeeriset tulokset</a></li>
<li class="chapter" data-level="4.3" data-path="täydentävät-pisteet.html"><a href="täydentävät-pisteet.html#esimerkki-3d--kartasta---saksan-ja-belgian-dimensiot"><i class="fa fa-check"></i><b>4.3</b> Esimerkki 3d- kartasta - Saksan ja Belgian dimensiot</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="yhteisvaikutusmuuttujat.html"><a href="yhteisvaikutusmuuttujat.html"><i class="fa fa-check"></i><b>5</b> Yhteisvaikutusmuuttujat</a><ul>
<li class="chapter" data-level="5.1" data-path="yhteisvaikutusmuuttujat.html"><a href="yhteisvaikutusmuuttujat.html#ikä-ja-sukupuoli"><i class="fa fa-check"></i><b>5.1</b> Ikä ja sukupuoli</a></li>
<li class="chapter" data-level="5.2" data-path="yhteisvaikutusmuuttujat.html"><a href="yhteisvaikutusmuuttujat.html#ikä-sukupuoli-ja-maa"><i class="fa fa-check"></i><b>5.2</b> Ikä, sukupuoli ja maa</a></li>
<li class="chapter" data-level="5.3" data-path="yhteisvaikutusmuuttujat.html"><a href="yhteisvaikutusmuuttujat.html#stabiilisuus"><i class="fa fa-check"></i><b>5.3</b> Stabiilisuus</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="osajoukon-korrespondenssianalyysi.html"><a href="osajoukon-korrespondenssianalyysi.html"><i class="fa fa-check"></i><b>6</b> Osajoukon korrespondenssianalyysi</a></li>
<li class="chapter" data-level="7" data-path="monimuuttuja-korrespondenssianalyysi-mca.html"><a href="monimuuttuja-korrespondenssianalyysi-mca.html"><i class="fa fa-check"></i><b>7</b> Monimuuttuja-korrespondenssianalyysi (MCA)</a><ul>
<li class="chapter" data-level="7.1" data-path="monimuuttuja-korrespondenssianalyysi-mca.html"><a href="monimuuttuja-korrespondenssianalyysi-mca.html#pinotut-ja-yhdistetyt-taulukot"><i class="fa fa-check"></i><b>7.1</b> Pinotut ja yhdistetyt taulukot</a></li>
<li class="chapter" data-level="7.2" data-path="monimuuttuja-korrespondenssianalyysi-mca.html"><a href="monimuuttuja-korrespondenssianalyysi-mca.html#mca---monimuuttujakorrespondenssianalyysi"><i class="fa fa-check"></i><b>7.2</b> MCA - monimuuttujakorrespondenssianalyysi</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="yhteenveto.html"><a href="yhteenveto.html"><i class="fa fa-check"></i><b>8</b> Yhteenveto</a></li>
<li class="chapter" data-level="" data-path="lähteet.html"><a href="lähteet.html"><i class="fa fa-check"></i>Lähteet</a></li>
<li class="appendix"><span><b>Liitteet</b></span></li>
<li class="chapter" data-level="" data-path="liite-1-korrespondenssianalyysin-teoriaa.html"><a href="liite-1-korrespondenssianalyysin-teoriaa.html"><i class="fa fa-check"></i>Liite 1: Korrespondenssianalyysin teoriaa</a><ul>
<li class="chapter" data-level="" data-path="liite-1-korrespondenssianalyysin-teoriaa.html"><a href="liite-1-korrespondenssianalyysin-teoriaa.html#korrespondenssianalyysin-perusyhtälöt-ja-kaavat"><i class="fa fa-check"></i>Korrespondenssianalyysin perusyhtälöt ja kaavat</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="liite-2-tekninen-ympäristö-ja-bookdown-paketti.html"><a href="liite-2-tekninen-ympäristö-ja-bookdown-paketti.html"><i class="fa fa-check"></i>Liite 2: Tekninen ympäristö ja Bookdown-paketti</a></li>
<li class="chapter" data-level="" data-path="liite-3-r-koodi.html"><a href="liite-3-r-koodi.html"><i class="fa fa-check"></i>Liite 3: R - koodi</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Korrespondenssianalyysi - graafinen ja geometrinen data-analyysin menetelmä</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="osajoukon-korrespondenssianalyysi" class="section level1">
<h1><span class="header-section-number">Luku 6</span> Osajoukon korrespondenssianalyysi</h1>
<p>Graafisessa data-analyysissä kuvien on oltava selkeitä, mutta
korrespondenssianalyysin ja monimuutujakorrespondenssianalyysin kartat ovat usein
liian täynnä pisteitä. Ongelmaa voi lievenätää jättämällä pois ratkaisuun vain
vähän vaikutttavia pisteitä, keksimällä mahdollisimman lyhyitä symboleja
muuttujille tai rajaamalla kuvaa. Ongelma on kuitenkin syvempi, usein kartta
kertoo aika yllätyksettömän ja ilmeisen tarinan. Kiinnostavammat yhteydet
pysyvät piilossa ylemmissä dimensioissa. MCA-kartan perusongelma on se, että
siinä yritetään esittää monia erityyppisiä yhteyksiä simultaanisesti ja nämä
yhteydet eivät ole “isolated to particular dimensions”
( <span class="citation">M. Greenacre ja Pardo (<a href="lähteet.html#ref-RefWorks:doc:5a857a44e4b0ed2d44664d87" role="doc-biblioref">2006</a>)</span> , 198).</p>
<p>Osajoukon korrespondenssianalyysi (subset CA, subset MCA) on yksi vastaus tähän
pulmaan. Teoreettiset perusteet on esitetty Greenacren ja Pardon artikkelissa
<span class="citation">(M. Greenacre ja Pardo <a href="lähteet.html#ref-RefWorks:doc:5a857a44e4b0ed2d44664d87" role="doc-biblioref">2006</a>)</span> ja sen laajennetussa versiossa (emt.),
esimerkkiaineistona ISSP:n 1994 data. Selkeä oppikirjaesitys on CAiP (ss. 161-).</p>
<p>Eräs selkeä sovelluskohde yhteiskuntatieteellisissä kyselyaineistoissa on
puuttuvien vastausten analyysi, johon palataan seuraavassa luvussa.</p>
<p>Osajoukon korrespondenssianlyysin idea on säilyttää koko aineiston massat ja
khii2-etäisyyksien painot mutta analysoida vain osaa aineistosta. Koko aineiston
sentroidi säilyy kartan keksipisteenä. Osajoukkojen inertioiden summa on koko
aineiston inertia.</p>
<p>Osajoukon voi valita havaintojen tai muuttujien suhteen. Täydentäviä pisteitä
voi helposti lisätä kartalle , jos ne eivät kuulu siihen joukkoon josta
osajoukko on valittu. Osajoukon profiilit muuttuvat, niiden summa ei enään ole
yksi ja barysentristä periaatetta ei voi suoraan käyttää täydentävän pisteen
koordinaattien laskemiseen. Tässä esimerkissä emme voi suoraan ca-paketin avulla
sijoittaa esimerkiksi maapisteitä kartoille.</p>
<p>Kartan <a href="yhteisvaikutusmuuttujat.html#fig:maagaCA1map1">5.2</a> avulla on helppo jakaa aineisto aluksi vain kahteen ryhmään.
Suomi, Tanska ja Saksa ovat pääakselin oikealla puolella.
Bulgaria ja Unkari yhdessä Belgian kanssa ovat toinen ryhmä.</p>
<div class="figure" style="text-align: center"><span id="fig:maagaCA2sub2map1"></span>
<img src="JH_capaper_files/figure-html/maagaCA2sub2map1-1.png" alt="Ikä, sukupuoli ja maa:Tanska-Saksa-Suomi" width="90%" />
<p class="caption">
Kuva 6.1: Ikä, sukupuoli ja maa:Tanska-Saksa-Suomi
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:maagaCA2sub2map3"></span>
<img src="JH_capaper_files/figure-html/maagaCA2sub2map3-1.png" alt="Ikä, sukupuoli ja maa:Tanska-Saksa-Suomi" width="90%" />
<p class="caption">
Kuva 6.2: Ikä, sukupuoli ja maa:Tanska-Saksa-Suomi
</p>
</div>
<p>Karttoja <a href="osajoukon-korrespondenssianalyysi.html#fig:maagaCA2sub2map1">6.1</a> ja <a href="osajoukon-korrespondenssianalyysi.html#fig:maagaCA2sub2map3">6.2</a> joutuu katsomaan
aika tarkkaan ennenkuin uskoo, että akseleiden skaalaus on akateeminen pulma
vailla käytännön merkitystä (kts.luku 3.3.4). Dataa analysoidaan graafisesti, ja kuvat
<em>näyttävät</em> erilaisilta. Pääakselien inertioiden neliöjuuret ovat
0.327 ja 0.158,
sarakkeiden etäisyyksiä voisi tulkita myös kontribuutiokuvista.</p>
<div class="figure" style="text-align: center"><span id="fig:maagaCA2sub2map2"></span>
<img src="JH_capaper_files/figure-html/maagaCA2sub2map2-1.png" alt="Ikä, sukupuoli ja maa:Tanska-Saksa-Suomi" width="90%" />
<p class="caption">
Kuva 6.3: Ikä, sukupuoli ja maa:Tanska-Saksa-Suomi
</p>
</div>
<p><strong>k</strong> Rivipisteiden tulkinta</p>
<pre><code>## 
## Principal inertias (eigenvalues):
## 
##  dim    value      %   cum%   scree plot               
##  1      0.107090  74.6  74.6  *******************      
##  2      0.024985  17.4  92.0  ****                     
##  3      0.006594   4.6  96.6  *                        
##  4      0.004882   3.4 100.0  *                        
##         -------- -----                                 
##  Total: 0.143551 100.0                                 
## 
## 
## Rows:
##      name   mass  qlt  inr    k=1 cor ctr    k=2 cor ctr  
## 1  | DEf1 |   13  467    5 |  -12   3   0 | -162 464  13 |
## 2  | DEf2 |   15  930   19 | -387 799  21 | -157 131  14 |
## 3  | DEf3 |   19  919   25 | -271 385  13 | -318 533  76 |
## 4  | DEf4 |   23  993   25 | -376 913  30 | -111  80  11 |
## 5  | DEf5 |   17  893   13 | -271 641  11 | -169 252  19 |
## 6  | DEf6 |   23   48   15 |  -64  42   1 |   24   6   1 |
## 7  | DEm1 |   13  827    8 |  172 345   3 | -203 482  21 |
## 8  | DEm2 |   13  855    8 |   93  96   1 | -260 759  34 |
## 9  | DEm3 |   15  874    7 |  -13   3   0 | -238 871  34 |
## 10 | DEm4 |   21  285    8 |   25  11   0 | -126 274  13 |
## 11 | DEm5 |   19  684   10 |  116 174   2 | -198 510  30 |
## 12 | DEm6 |   22  750   22 |  190 260   8 |  261 490  61 |
## 13 | DKf1 |   10  979   27 | -603 949  35 |  107  30   5 |
## 14 | DKf2 |   14  996   89 | -955 960 115 |  184  36  18 |
## 15 | DKf3 |   17  985   98 | -885 933 122 |  210  53  29 |
## 16 | DKf4 |   18  983  104 | -889 950 132 |  165  33  20 |
## 17 | DKf5 |   16 1000   69 | -792 988  92 |   86  12   5 |
## 18 | DKf6 |   12  834   17 | -386 745  17 |  133  89   9 |
## 19 | DKm1 |   15  978   13 | -342 971  17 |   30   7   1 |
## 20 | DKm2 |   13  997   79 | -938 988 104 |   90   9   4 |
## 21 | DKm3 |   13  989   52 | -743 989  69 |  -14   0   0 |
## 22 | DKm4 |   15  962   36 | -563 952  45 |   57  10   2 |
## 23 | DKm5 |   13  682   16 | -314 543  12 |  159 139  13 |
## 24 | DKm6 |   15  291    9 |   45  22   0 |  158 269  15 |
## 25 | FIf1 |   12  951   20 | -346 478  13 | -345 474  55 |
## 26 | FIf2 |   12  941   48 | -680 788  50 | -300 153  42 |
## 27 | FIf3 |   12  952   24 | -335 370  12 | -420 582  82 |
## 28 | FIf4 |   14  999   25 | -323 426  14 | -375 573  82 |
## 29 | FIf5 |   17  982   14 | -185 299   6 | -280 683  55 |
## 30 | FIf6 |   11  704   13 |  217 274   5 | -271 430  33 |
## 31 | FIm1 |    7  624    8 |  -40  10   0 | -323 614  30 |
## 32 | FIm2 |    9  984   26 | -525 640  22 | -385 344  52 |
## 33 | FIm3 |    9  990   12 | -279 412   6 | -331 578  38 |
## 34 | FIm4 |   13  944   11 |   90  67   1 | -324 877  54 |
## 35 | FIm5 |   12  722   14 |  267 426   8 | -222 295  23 |
## 36 | FIm6 |    9  911   11 |  373 785  12 | -150 126   8 |
## 
## Columns:
##     name   mass  qlt  inr    k=1 cor ctr    k=2 cor ctr  
## 1 |    S |   99  731  107 |  276 493  71 |  192 238 147 |
## 2 |    s |  238  832  114 |  218 688 105 |  100 144  94 |
## 3 |      |  168  647   88 |  208 576  68 |   73  70  35 |
## 4 |    e |  261  992  135 |   85  96  17 | -258 896 697 |
## 5 |    E |  234 1000  556 | -582 992 739 |   53   8  27 |</code></pre>
<p><strong>Tulkintaa</strong></p>
<p>Kolmen maan osajoukon ratkaisussa 2. dimensiolla (maltillinen liberaali - tiukka konservatiivi) on
inertiasta 17 prosenttia, edellä ollut paljon yksiulotteisempia ratkaisuja. Huono kvaliteetti (qlt)
on ryhmillä DEf1 (467) ja DEf6 (48), DEm4 (285). Tanskan havainnoista vanhimmat miehet
(DKm6,291) ovat kaikkein huonoimmin esitettyjä ratkaisussa, ja hieman nuoremmatkin
(DKm5, 682). Suomen aineistossa vain nuoret miehet (FIm1, 624) on esitetty kartalla
huonosti. Kaksi dimensiot selittävät osajoukon kokonaishajonnasta 92%, mutta muutaman
ryhmän hajonta on muissa dimensioissa. Saksan naisten iäkkäin ikäluokka (DEf6)
ja keski-ikäisen miehet (DEm4) vain näyttävät olevan lähekkäin origon tuntumassa,
samoin muutama muu huonosti tasoon sijoitettu piste.</p>
<p>Huonosti kuvatuista pisteistäkuva ei oikeastaan mitään muuta.</p>
<p>Sarakkeet on esitetty kohtalaisen hyvin, ja symmetrisessä kartassa tärkeimmälle
dimensioille projisodut sarakepisteet ovat odotetussa järjestyksessä.</p>
<p>Kontribuutiokartasta nähdään, että tärkein kontrasti on tiukan erimielisyyden (E)
ja kaikkien muiden vastausvaihtoehtojen välillä. Epävarmojen tai maltillisten (e)
kontrasti hallitsee toista dimensiota, erityisesti S- ja s- kategorioiden kanssa.
Samalla kuvasta näkee (ja numeerisist tuloksista voi vahvistaa), että S-piste on
on lähempänä (kulma on pienempi) pystyakselia. Kontribuutio on suurempi (147 vs.
71 x-akselille). Toisaalta x-akseli selittää selvästi suurimman osan kaikkien muiden
sarakepisteiden inertiasta, ja y-akseli taas lähes täysin e-pisteen inertian.</p>
<div class="figure" style="text-align: center"><span id="fig:maagaCA2sub3map1"></span>
<img src="JH_capaper_files/figure-html/maagaCA2sub3map1-1.png" alt="Ikä, sukupuoli ja maa: Belgia-Bulgaria - Unkari 1" width="90%" />
<p class="caption">
Kuva 6.4: Ikä, sukupuoli ja maa: Belgia-Bulgaria - Unkari 1
</p>
</div>
<p>Ensimmäisen dimension tulkinta pysyy samana, mutta nyt molemmat erimieliset
(E, e) vastauskategoriat ovat selvästi oikealla. Ne ovat lähes x-akselin päällä,
kun ensimmäisen osajoukon kartalla e-sarake oli oikealla ja alhaalla kontrastina
S- ja s- vastauksille ja myös neutraalille vaihtoehdolle. Kartan toinen dimenisio
erottelee nyt tiukasti ja lievemmin samaa mieltä olevat, neutraali vaihtoehto
jää väliin.</p>
<p>Belgian nuoremmat ikäluokat ovat liberaalilla puolella, ja kiinnostavasti
kaksi vanhinta miesten ryhmää on pystysuunnassa kaikkein maltillisimpia.
Bulgarian ja Unkarin pisteen ovat x-akselilla tiukasti konservatiivisa.
Vaihtelua on maltillisemman ja jyrkemmän konservatiivisuuden välillä
pystysuuntaan. Toisen dimension kontrasti on myös hieman yllättäen
Bulgarian nuorimpien naisten (BGf1) Unkarin vanhimpiten naisten (HUf6)
välillä.</p>
<p>Kuvan <a href="osajoukon-korrespondenssianalyysi.html#fig:maagaCA2sub2map2">6.3</a> tapaan ei Bulgarian ja Unkarin
ikäluokkia kannata yhdistää. Järjestys toki löytyy, mutta ei ollenkaan
niin selkeä. Saksan naisten ikäluokkakuva alkaa erkaantua hieman Suomen ja Taskan
hyvin samanalaisista kuvioista. Saksan miehillä on jo eroja paljon toisen
dimension suuntaan, Unkarin ja Bulgarian osajoukkojen erot ovat lähes
pelkästään pystysuoria.</p>
<p>Suhteellinen kontribuutio eli pisteen laatu (numeerisissa
tuloksissa “cor”) on esitetty värisävynä. Sarakkeista e ja “?” on
esitetty huonosti, riveistä Belgian nuorimmat miehet ja naiset.</p>
<div class="figure" style="text-align: center"><span id="fig:maagaCA2sub3map2"></span>
<img src="JH_capaper_files/figure-html/maagaCA2sub3map2-1.png" alt="Ikä, sukupuoli ja maa: Belgia-Bulgaria - Unkari 2" width="90%" />
<p class="caption">
Kuva 6.5: Ikä, sukupuoli ja maa: Belgia-Bulgaria - Unkari 2
</p>
</div>
<p>Kontribuutiokartta (fig:maagaCA2sub3map2) eroaa kartasta (fig:maagaCA2sub2map3)
kolmen akselin (E, S ja s) tasapainosemmalla vaikutuksella ratkaisuun. Konservatiiviset
sarakepisteet ovat vaikuttavampia kuin E, maltillinen liberaali (s) ja neutraali vaihtoehto
vaikuttavat vähemmän.</p>
<p><strong>k</strong> Yksityiskohdat ovat kiinnostavia, mutta graafisen analyysin
päätavoite on yleiskuva. Tässä ekspolratiivinen data-analyysi
kuitenkin kulkee hieman eri polkuja kuin tavaniomainen tilastollisten
mallien analyysi. Seuratataan minne data kuljettaa, etstiään uusia
näkökulmia. Iän ja sukupuolen yhteys vastauksiin on rakenteeltaan erilainen,
se ei ole ongelma vaan datan ominaisuus.</p>
<pre><code>## 
## Principal inertias (eigenvalues):
## 
##  dim    value      %   cum%   scree plot               
##  1      0.086111  72.0  72.0  ******************       
##  2      0.018841  15.8  87.8  ****                     
##  3      0.011172   9.3  97.1  **                       
##  4      0.003477   2.9 100.0  *                        
##         -------- -----                                 
##  Total: 0.119602 100.0                                 
## 
## 
## Rows:
##      name   mass  qlt  inr    k=1 cor ctr    k=2 cor ctr  
## 1  | BEf1 |   14  152   19 | -156 152   4 |    2   0   0 |
## 2  | BEf2 |   24  826   24 | -313 824  28 |   13   1   0 |
## 3  | BEf3 |   21  623    7 |  -90 201   2 |  130 422  19 |
## 4  | BEf4 |   24  556    6 |  -65 155   1 |  105 401  14 |
## 5  | BEf5 |   23  355   11 |  115 227   3 |   86 128   9 |
## 6  | BEf6 |   23  810   37 |  396 810  41 |   10   0   0 |
## 7  | BEm1 |   11  288   21 |  246 274   8 |   55  14   2 |
## 8  | BEm2 |   17  333   11 | -144 271   4 |   68  61   4 |
## 9  | BEm3 |   20  531    2 |    6   4   0 |   75 528   6 |
## 10 | BEm4 |   22  620   11 |  197 618  10 |   -8   1   0 |
## 11 | BEm5 |   22  917   18 |  243 620  15 | -168 297  33 |
## 12 | BEm6 |   26  977   33 |  347 782  36 | -173 195  41 |
## 13 | BGf1 |    5  979   23 |  557 549  18 | -492 430  63 |
## 14 | BGf2 |    8  974   32 |  649 875  38 | -219  99  20 |
## 15 | BGf3 |   12 1000   46 |  633 844  54 | -271 155  45 |
## 16 | BGf4 |   10  847   25 |  496 847  30 |    7   0   0 |
## 17 | BGf5 |   14  961   50 |  618 894  62 | -168  66  21 |
## 18 | BGf6 |   18  939   71 |  658 931  92 |  -60   8   4 |
## 19 | BGm1 |    5  999   15 |  608 912  19 |  188  87   9 |
## 20 | BGm2 |    6  892   21 |  526 703  20 | -273 189  25 |
## 21 | BGm3 |    8  994   41 |  677 746  43 | -390 247  64 |
## 22 | BGm4 |    8  669   25 |  508 666  23 |  -34   3   0 |
## 23 | BGm5 |   10  949   24 |  516 947  32 |  -22   2   0 |
## 24 | BGm6 |    9  978   58 |  748 737  60 | -428 241  89 |
## 25 | HUf1 |    7  888   20 |  493 681  19 |  271 207  26 |
## 26 | HUf2 |   11  762   25 |  406 589  20 |  220 173  27 |
## 27 | HUf3 |   12  916   39 |  525 688  37 |  301 227  56 |
## 28 | HUf4 |   11  970   40 |  528 651  36 |  370 319  81 |
## 29 | HUf5 |   12  985   29 |  490 802  32 |  234 183  34 |
## 30 | HUf6 |   13  933   75 |  655 614  64 |  472 319 151 |
## 31 | HUm1 |    6  948   12 |  455 871  14 |  135  77   6 |
## 32 | HUm2 |    9  902   24 |  312 313  10 |  428 589  90 |
## 33 | HUm3 |   13  945   26 |  477 938  33 |  -41   7   1 |
## 34 | HUm4 |   10  965   22 |  503 960  29 |   36   5   1 |
## 35 | HUm5 |   13  993   26 |  478 916  33 |  139  77  13 |
## 36 | HUm6 |    8  839   33 |  560 622  29 |  331 217  46 |
## 
## Columns:
##     name   mass  qlt  inr    k=1 cor ctr    k=2 cor ctr  
## 1 |    S |   99  944  214 |  351 479 142 |  346 465 630 |
## 2 |    s |  238  942  247 |  297 711 244 | -169 231 362 |
## 3 |      |  168  435  107 |  180 426  63 |   26   9   6 |
## 4 |    e |  261  640   65 | -138 639  57 |   -4   0   0 |
## 5 |    E |  234  966  368 | -426 965 494 |   10   1   1 |</code></pre>
<p><strong>edit: tässä toistoa</strong></p>
<p>Kahden osajoukon inertioiden summa on sama kuin koko aineiston
( 0.144 + 0.12 = 0.263), Selitysasteet
nousevat hieman, ja aineiston riippuvuuden rakenteesta saadaaan esiin selviä eroja.
Osajoukkojen analyysi täydentää ja tarkentaa yleiskuvaa (@ref:fig:maagaCA1map1)</p>
<p>Belgian pisteistä osalla on huono kvaliteetti (BEf1, BEf5,BEm1, BEm2). Bulgaria ja
Unkari hyvin esitetty. Belgia on pulmallinen tapaus, ehkä taas omissa dimensioissaan.
Belgian poikkeavuus (annetulla aluejaolla) on kiinnostava havainto, korrespondenssianalyysin
tavoite ei ole pelkästään kohtuullisen luotettava yleiskuva taulukon riippuvuuksista. Poikkeavat
havainnot eivät ole ongelma, vaan datan ominaisuus.</p>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="yhteisvaikutusmuuttujat.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="monimuuttuja-korrespondenssianalyysi-mca.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["JH_capaper.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
