<!DOCTYPE html>
<html lang="fi" xml:lang="fi">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Luku 5 Yhteisvaikutusmuuttujat | Korrespondenssianalyysi - graafinen ja geometrinen data-analyysin menetelmä</title>
  <meta name="description" content="Tutkielma korrespondenssianalyysistä graafisena data-analyysin menetelmänä." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Luku 5 Yhteisvaikutusmuuttujat | Korrespondenssianalyysi - graafinen ja geometrinen data-analyysin menetelmä" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Tutkielma korrespondenssianalyysistä graafisena data-analyysin menetelmänä." />
  <meta name="github-repo" content="hirjus/capaper" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Luku 5 Yhteisvaikutusmuuttujat | Korrespondenssianalyysi - graafinen ja geometrinen data-analyysin menetelmä" />
  
  <meta name="twitter:description" content="Tutkielma korrespondenssianalyysistä graafisena data-analyysin menetelmänä." />
  

<meta name="author" content="Jussi Hirvonen" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="täydentävät-pisteet.html"/>
<link rel="next" href="osajoukon-korrespondenssianalyysi.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Alkutoimia</a></li>
<li class="chapter" data-level="1" data-path="johdanto.html"><a href="johdanto.html"><i class="fa fa-check"></i><b>1</b> Johdanto</a><ul>
<li class="chapter" data-level="1.1" data-path="johdanto.html"><a href="johdanto.html#tutkielman-tavoite"><i class="fa fa-check"></i><b>1.1</b> Tutkielman tavoite</a></li>
<li class="chapter" data-level="1.2" data-path="johdanto.html"><a href="johdanto.html#tärkeimmät-lähteet-ja-ohjelmistot"><i class="fa fa-check"></i><b>1.2</b> Tärkeimmät lähteet ja ohjelmistot</a></li>
<li class="chapter" data-level="1.3" data-path="johdanto.html"><a href="johdanto.html#korrespondenssianalyysin-historiaa"><i class="fa fa-check"></i><b>1.3</b> Korrespondenssianalyysin historiaa</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>2</b> Data</a><ul>
<li class="chapter" data-level="2.1" data-path="data.html"><a href="data.html#aineiston-rajaaminen-maat-ja-muuttujat"><i class="fa fa-check"></i><b>2.1</b> Aineiston rajaaminen maat ja muuttujat</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="yksinkertainen-korrespondenssianalyysi.html"><a href="yksinkertainen-korrespondenssianalyysi.html"><i class="fa fa-check"></i><b>3</b> Yksinkertainen korrespondenssianalyysi</a><ul>
<li class="chapter" data-level="3.1" data-path="yksinkertainen-korrespondenssianalyysi.html"><a href="yksinkertainen-korrespondenssianalyysi.html#äiti-töissä---kärsiikö-lapsi"><i class="fa fa-check"></i><b>3.1</b> Äiti töissä - kärsiikö lapsi?</a></li>
<li class="chapter" data-level="3.2" data-path="yksinkertainen-korrespondenssianalyysi.html"><a href="yksinkertainen-korrespondenssianalyysi.html#korrespondenssianalyysin-esimerkki-symmetrinen-kartta"><i class="fa fa-check"></i><b>3.2</b> Korrespondenssianalyysin esimerkki: symmetrinen kartta</a></li>
<li class="chapter" data-level="3.3" data-path="yksinkertainen-korrespondenssianalyysi.html"><a href="yksinkertainen-korrespondenssianalyysi.html#korrespondenssianalyysin-peruskäsitteet"><i class="fa fa-check"></i><b>3.3</b> Korrespondenssianalyysin peruskäsitteet</a><ul>
<li class="chapter" data-level="3.3.1" data-path="yksinkertainen-korrespondenssianalyysi.html"><a href="yksinkertainen-korrespondenssianalyysi.html#asymmetrinen-kartta-ja-ideaalipisteet"><i class="fa fa-check"></i><b>3.3.1</b> Asymmetrinen kartta ja ideaalipisteet</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="yksinkertainen-korrespondenssianalyysi.html"><a href="yksinkertainen-korrespondenssianalyysi.html#kontribuutiot-kartalla"><i class="fa fa-check"></i><b>3.4</b> Kontribuutiot kartalla</a></li>
<li class="chapter" data-level="3.5" data-path="yksinkertainen-korrespondenssianalyysi.html"><a href="yksinkertainen-korrespondenssianalyysi.html#massat"><i class="fa fa-check"></i><b>3.5</b> Massat</a></li>
<li class="chapter" data-level="3.6" data-path="yksinkertainen-korrespondenssianalyysi.html"><a href="yksinkertainen-korrespondenssianalyysi.html#karttojen-erot"><i class="fa fa-check"></i><b>3.6</b> Karttojen erot</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="täydentävät-pisteet.html"><a href="täydentävät-pisteet.html"><i class="fa fa-check"></i><b>4</b> Täydentävät pisteet</a><ul>
<li class="chapter" data-level="4.1" data-path="täydentävät-pisteet.html"><a href="täydentävät-pisteet.html#saksan-ja-belgian-alueet"><i class="fa fa-check"></i><b>4.1</b> Saksan ja Belgian alueet</a></li>
<li class="chapter" data-level="4.2" data-path="täydentävät-pisteet.html"><a href="täydentävät-pisteet.html#korrespondenssianalyysin-numeeriset-tulokset"><i class="fa fa-check"></i><b>4.2</b> Korrespondenssianalyysin numeeriset tulokset</a></li>
<li class="chapter" data-level="4.3" data-path="täydentävät-pisteet.html"><a href="täydentävät-pisteet.html#esimerkki-3d--kartasta---saksan-ja-belgian-dimensiot"><i class="fa fa-check"></i><b>4.3</b> Esimerkki 3d- kartasta - Saksan ja Belgian dimensiot</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="yhteisvaikutusmuuttujat.html"><a href="yhteisvaikutusmuuttujat.html"><i class="fa fa-check"></i><b>5</b> Yhteisvaikutusmuuttujat</a><ul>
<li class="chapter" data-level="5.1" data-path="yhteisvaikutusmuuttujat.html"><a href="yhteisvaikutusmuuttujat.html#ikä-ja-sukupuoli"><i class="fa fa-check"></i><b>5.1</b> Ikä ja sukupuoli</a></li>
<li class="chapter" data-level="5.2" data-path="yhteisvaikutusmuuttujat.html"><a href="yhteisvaikutusmuuttujat.html#ikä-sukupuoli-ja-maa"><i class="fa fa-check"></i><b>5.2</b> Ikä, sukupuoli ja maa</a></li>
<li class="chapter" data-level="5.3" data-path="yhteisvaikutusmuuttujat.html"><a href="yhteisvaikutusmuuttujat.html#stabiilisuus"><i class="fa fa-check"></i><b>5.3</b> Stabiilisuus</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="osajoukon-korrespondenssianalyysi.html"><a href="osajoukon-korrespondenssianalyysi.html"><i class="fa fa-check"></i><b>6</b> Osajoukon korrespondenssianalyysi</a></li>
<li class="chapter" data-level="7" data-path="monimuuttuja-korrespondenssianalyysi-mca.html"><a href="monimuuttuja-korrespondenssianalyysi-mca.html"><i class="fa fa-check"></i><b>7</b> Monimuuttuja-korrespondenssianalyysi (MCA)</a><ul>
<li class="chapter" data-level="7.1" data-path="monimuuttuja-korrespondenssianalyysi-mca.html"><a href="monimuuttuja-korrespondenssianalyysi-mca.html#pinotut-ja-yhdistetyt-taulukot-stacked-and-concatenated-tables"><i class="fa fa-check"></i><b>7.1</b> Pinotut ja yhdistetyt taulukot (stacked and concatenated tables)</a></li>
<li class="chapter" data-level="7.2" data-path="monimuuttuja-korrespondenssianalyysi-mca.html"><a href="monimuuttuja-korrespondenssianalyysi-mca.html#matched-matrices"><i class="fa fa-check"></i><b>7.2</b> Matched matrices</a></li>
<li class="chapter" data-level="7.3" data-path="monimuuttuja-korrespondenssianalyysi-mca.html"><a href="monimuuttuja-korrespondenssianalyysi-mca.html#mca---monimuuttujakorrespondenssianalyysi"><i class="fa fa-check"></i><b>7.3</b> MCA - monimuuttujakorrespondenssianalyysi</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="yhteenveto.html"><a href="yhteenveto.html"><i class="fa fa-check"></i><b>8</b> Yhteenveto</a></li>
<li class="chapter" data-level="" data-path="liitteet.html"><a href="liitteet.html"><i class="fa fa-check"></i>Liitteet</a><ul>
<li class="chapter" data-level="" data-path="liitteet.html"><a href="liitteet.html#liite-1-korrespondenssianalyysin-teoriaa"><i class="fa fa-check"></i>Liite 1: Korrespondenssianalyysin teoriaa</a><ul>
<li class="chapter" data-level="" data-path="liitteet.html"><a href="liitteet.html#korrespondenssianalyysin-perusyhtälöt-ja-kaavat"><i class="fa fa-check"></i>Korrespondenssianalyysin perusyhtälöt ja kaavat</a></li>
<li class="chapter" data-level="" data-path="liitteet.html"><a href="liitteet.html#matriisit-ja-niiden-havainnollistaminen"><i class="fa fa-check"></i>Matriisit ja niiden havainnollistaminen</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="liitteet.html"><a href="liitteet.html#liite-2-suomenkielinen-lomake-esimerkki"><i class="fa fa-check"></i>Liite 2: Suomenkielinen lomake (esimerkki)</a></li>
<li class="chapter" data-level="" data-path="liitteet.html"><a href="liitteet.html#liite-3-tekninen-ympäristö-ja-bookdown-paketti"><i class="fa fa-check"></i>Liite 3: Tekninen ympäristö ja Bookdown-paketti</a></li>
<li class="chapter" data-level="" data-path="liitteet.html"><a href="liitteet.html#liite-4-r---koodi"><i class="fa fa-check"></i>Liite 4: R - koodi</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="lähteet.html"><a href="lähteet.html"><i class="fa fa-check"></i>Lähteet</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Korrespondenssianalyysi - graafinen ja geometrinen data-analyysin menetelmä</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="yhteisvaikutusmuuttujat" class="section level1">
<h1><span class="header-section-number">Luku 5</span> Yhteisvaikutusmuuttujat</h1>
<p><strong>ks</strong> “Interactive coding”</p>
<p><strong>edit</strong> Yksinkertaisin tapa ottaa muita muuttujia mukaan analyysiin.</p>
<p><strong>k</strong> Kaksi yhteisvaikutusmuuttujaan (MG “interactive coding”), sukupuoli ja
ikäluokka/kohortti ja tämän muuttujan yhdistäminen maa-muuttujaan.</p>
<p><strong>k</strong> Poikkileikkausaineistossa vastaajaan ikä kuvaa sekä ikää että mitä erilaisimipia
sukupolvivaikutuksia. Ei voi oikein erottaa toisistaan. Vastaajat ovat elämänsä eri
vaiheissa kohdanneet lukuisia rajuja muutoksia toisen maailmansodan jälkeen. Nähtiin
jo edellisessä jaksossa!</p>
<p>Poikkileikkausaineistossa vastaajan ikä kertoo ikäluokan (kohortin), vastaajat ovat
kokeen esim. kaksi mullistusten vuotta elämänsä eri vaiheissa. Kaksin nuorinta ikäluokka
on ollut 1990 alle 14-vuotiaita ja vanhin ikäluokka yli 44-vuotiaita. Finannsikriisin
vuonna 2008 toiseksi nuorin ikäluokka on ollut 22-31 vuotiaita, ja kaksi vanhinta
yli 51-vuotiaita.</p>
<div id="ikä-ja-sukupuoli" class="section level2">
<h2><span class="header-section-number">5.1</span> Ikä ja sukupuoli</h2>
<p><strong>edit</strong> Lyhyesti tämä, aineisto aggregoitu ikä- ja sukupuoliryhmiin.
<strong>edit</strong> Voi myös lisätä täydentävinä pisteinä “peruskarttaan”, ei tehdä.</p>
<p>Ikäluokat ovat (1=15-25, 2 =26-35, 3=36-45, 4=46-55, 5=56-65, 6= 66 tai vanhempi).
Vuorovaikutusmuuttuja ga koodataan f1,…, f6 ja m1,…,m6. Muuttujien nimet
kannattaa pitää mahdollisimman lyhyinä.</p>
<p>Ikäjäkauma painottuu kaikissa maissa jonkinverran vanhempiin ikäluokkiin.
Nuorempien ikäluokkien osuus on (alle 26-vuotiaat ja alle 26-35 - vuotiaat)
varsinkin Bulgariassa (BG) ja Unkarissa (HU) pieni.</p>
<p><strong>k</strong> Ikä- ja sukupuoliryhmät yli kaikkien maiden; profiilit keskiarvoja. Ei kovin
pätevää analyysiä, yleiskuva muuttujasta.</p>
<div class="figure" style="text-align: center"><span id="fig:gaCA1map"></span>
<img src="JH_capaper_files/figure-html/gaCA1map-1.png" alt="Q1b: ikäluokka ja sukupuoli" width="90%" />
<p class="caption">
Kuva 5.1: Q1b: ikäluokka ja sukupuoli
</p>
</div>
<pre><code>## 
## Principal inertias (eigenvalues):
## 
##  dim    value      %   cum%   scree plot               
##  1      0.037448  87.0  87.0  **********************   
##  2      0.003977   9.2  96.2  **                       
##  3      0.001041   2.4  98.6  *                        
##  4      0.000590   1.4 100.0                           
##         -------- -----                                 
##  Total: 0.043055 100.0                                 
## 
## 
## Rows:
##      name   mass  qlt  inr    k=1 cor ctr    k=2 cor ctr  
## 1  |   f1 |   60  990   36 | -125 614  25 |  -98 376 145 |
## 2  |   f2 |   83  997  163 | -289 983 185 |   35  14  25 |
## 3  |   f3 |   91  984   47 | -146 958  52 |   24  26  13 |
## 4  |   f4 |  101 1000   97 | -186 836  93 |   82 164 172 |
## 5  |   f5 |   98  879    4 |  -35 658   3 |   20 221  10 |
## 6  |   f6 |  100  951  176 |  256 866 175 |   80  85 162 |
## 7  |   m1 |   57  659   32 |   42  72   3 | -120 587 205 |
## 8  |   m2 |   66  977   57 | -187 946  62 |  -34  30  19 |
## 9  |   m3 |   78  457    5 |  -31 318   2 |  -20 139   8 |
## 10 |   m4 |   89  674   14 |   58 482   8 |  -37 192  30 |
## 11 |   m5 |   89  988   90 |  189 818  85 |  -86 170 166 |
## 12 |   m6 |   89  978  277 |  360 963 307 |   45  15  45 |
## 
## Columns:
##     name   mass  qlt  inr    k=1 cor ctr    k=2 cor ctr  
## 1 |    S |   99  915  128 |  196 695 102 |  110 220 304 |
## 2 |    s |  238  969  304 |  230 961 336 |   21   8  27 |
## 3 |      |  168  777   46 |   62 330  17 |  -73 447 223 |
## 4 |    e |  261  897   58 |  -68 473  32 |  -64 424 268 |
## 5 |    E |  234  997  464 | -286 962 513 |   55  35 177 |</code></pre>
<p><strong>k</strong> Kommentteja Galkusta:
Aika yksiuloitteinen (87 prosenttia ensimmäisellä dimensiolla!). Data on
“as it is”, ei ole vakioitu ga-luokkien kokoja (massat max(f4 101), min (m1 57)).</p>
<p>Miten pitäisi tulkita “oikealle kaatunut U - muoto” miehillä ja naisilla?
Järjestys ei toimi, S s-sarakkeen vasemmalla puolella. Miehet konservatiivisempia,
mutta maltillisempia? Nuorin ikäluokka on poikkeava. Epävarmoja tai maltillisesti
e, sitten loikka vasemmalle ja sieltä konservatiiviseen suuntaa oikealle. Naisilla
poikkeama f3 - f4. VAnhimmat ikäluokat tiukemmin konservatiivisa (f6, m6). Jos
vertaa sukupuolten eroja samassa ikäluokassa, on aika samanlainen (miehet
konservatiivisia, naiset liberaaleja). Naisista vain vanhin ikäluokka oikealla,
miehistä nuorin ja kolme vanhinta.</p>
<p>Tulkinnassa muistettava, että ikäluokat yli maiden. Voi verrata sekä
edellisiin maa-vertailuihin että maan, ikäluokan ja sukupuolen yhteisvaikutusmuuttujan
tuloksiin. MG tutkailee eri kysymyksellä tätä samaa asiaa, ja havaitsee että
(a) maiden erot suuria ja sukupuolten pieniä (b) naiset liberaalimpia kuin miehet.
** Viite?**</p>
<p>Numeeriset tulokset: nuorimpien miesten (qlt 659) ja erityisesti
keski-ikäisten miestén m3 (qlt 457) pisteet huonosti esitetty kartalla. Tulkitaan
myös cor ja ctr, riveille ja sarakkeille.</p>
</div>
<div id="ikä-sukupuoli-ja-maa" class="section level2">
<h2><span class="header-section-number">5.2</span> Ikä, sukupuoli ja maa</h2>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="yhteisvaikutusmuuttujat.html#cb6-1"></a>ISSP2012esim1b.dat &lt;-<span class="st"> </span><span class="kw">mutate</span>(ISSP2012esim1b.dat,</span>
<span id="cb6-2"><a href="yhteisvaikutusmuuttujat.html#cb6-2"></a>                             <span class="dt">maaga =</span> <span class="kw">paste</span>(maa, ga, <span class="dt">sep =</span> <span class="st">&quot;&quot;</span>))</span>
<span id="cb6-3"><a href="yhteisvaikutusmuuttujat.html#cb6-3"></a></span>
<span id="cb6-4"><a href="yhteisvaikutusmuuttujat.html#cb6-4"></a><span class="co"># tarkistus, muunnos ok</span></span>
<span id="cb6-5"><a href="yhteisvaikutusmuuttujat.html#cb6-5"></a><span class="co"># ISSP2012esim1b.dat %&gt;% tableX(maa, maaga)</span></span>
<span id="cb6-6"><a href="yhteisvaikutusmuuttujat.html#cb6-6"></a><span class="co"># head(ISSP2012esim2.dat)</span></span>
<span id="cb6-7"><a href="yhteisvaikutusmuuttujat.html#cb6-7"></a><span class="co"># str(ISSP2012esim2.dat)</span></span></code></pre></div>
<p><strong>edit</strong> Yksi vaikeaselkoinen kartta täynnä pisteitä, tihrustellaan.</p>
<div class="figure" style="text-align: center"><span id="fig:maagaCA1map1"></span>
<img src="JH_capaper_files/figure-html/maagaCA1map1-1.png" alt="Q1b: ikäluokka ja sukupuoli maittain" width="90%" />
<p class="caption">
Kuva 5.2: Q1b: ikäluokka ja sukupuoli maittain
</p>
</div>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="yhteisvaikutusmuuttujat.html#cb7-1"></a><span class="co"># Vilkaistaan numeerisia tuloksia, kopioidaan tekstiin jos on tarpeellista</span></span>
<span id="cb7-2"><a href="yhteisvaikutusmuuttujat.html#cb7-2"></a></span>
<span id="cb7-3"><a href="yhteisvaikutusmuuttujat.html#cb7-3"></a><span class="kw">print</span>(maagaCA1)</span></code></pre></div>
<pre><code>## 
##  Principal inertias (eigenvalues):
##            1        2        3        4       
## Value      0.184895 0.038751 0.024006 0.015502
## Percentage 70.26%   14.73%   9.12%    5.89%   
## 
## 
##  Rows:
##              BEf1      BEf2      BEf3      BEf4      BEf5     BEf6      BEm1
## Mass     0.014245  0.024315  0.021368  0.024438  0.022842 0.022719  0.011298
## ChiDist  0.401386  0.344292  0.199783  0.164967  0.240455 0.439918  0.469422
## Inertia  0.002295  0.002882  0.000853  0.000665  0.001321 0.004397  0.002490
## Dim. 1  -0.192908 -0.645510 -0.144265 -0.116669  0.308332 0.862093  0.661555
## Dim. 2  -1.625273 -0.897934 -0.480404 -0.223840 -0.203533 0.778887 -0.592620
##              BEm2      BEm3      BEm4      BEm5      BEm6      BGf1     BGf2
## Mass     0.016579  0.019894  0.021614  0.022350  0.025543  0.004912 0.007860
## ChiDist  0.276047  0.102584  0.250249  0.308070  0.392168  0.751086 0.693373
## Inertia  0.001263  0.000209  0.001354  0.002121  0.003928  0.002771 0.003779
## Dim. 1  -0.263692  0.040639  0.524364  0.593355  0.809427  1.272436 1.489306
## Dim. 2  -0.632522 -0.146484 -0.498708 -0.319489 -0.023713 -0.047377 0.300670
##             BGf3      BGf4     BGf5     BGf6     BGm1      BGm2     BGm3
## Mass    0.011544  0.010438 0.014000 0.018298 0.004544  0.006263 0.007982
## ChiDist 0.688564  0.538800 0.653467 0.681719 0.636676  0.627620 0.784126
## Inertia 0.005473  0.003030 0.005978 0.008504 0.001842  0.002467 0.004908
## Dim. 1  1.435410  1.206311 1.417403 1.458638 1.387090  1.295443 1.523242
## Dim. 2  0.380068 -0.199915 0.334139 0.942930 0.805581 -0.659426 0.420697
##              BGm4     BGm5     BGm6      DEf1      DEf2      DEf3      DEf4
## Mass     0.007737 0.010316 0.009210  0.012526  0.014737  0.018666  0.022842
## ChiDist  0.622138 0.529671 0.871456  0.237411  0.432439  0.436045  0.393174
## Inertia  0.002995 0.002894 0.006995  0.000706  0.002756  0.003549  0.003531
## Dim. 1   1.256092 1.217661 1.630600 -0.094359 -0.964139 -0.773449 -0.906287
## Dim. 2  -0.411230 0.106062 0.934896 -0.758320 -0.302962 -1.138600 -0.093489
##              DEf5      DEf6      DEm1      DEm2      DEm3      DEm4      DEm5
## Mass     0.016579  0.022719  0.012649  0.012649  0.014982  0.021122  0.018789
## ChiDist  0.337893  0.312735  0.292550  0.298896  0.255414  0.239923  0.277383
## Inertia  0.001893  0.002222  0.001083  0.001130  0.000977  0.001216  0.001446
## Dim. 1  -0.690438 -0.131007  0.288893  0.088588 -0.149437 -0.002440  0.176330
## Dim. 2  -0.443502  0.459553 -1.271559 -1.314308 -1.064830 -0.450858 -1.024467
##             DEm6      DKf1      DKf2      DKf3      DKf4      DKf5      DKf6
## Mass    0.022228  0.010193  0.013509  0.016701  0.017930  0.015719  0.012158
## ChiDist 0.373055  0.618958  0.974207  0.915861  0.912001  0.796636  0.447079
## Inertia 0.003093  0.003905  0.012821  0.014009  0.014913  0.009976  0.002430
## Dim. 1  0.566840 -1.318547 -2.065738 -1.896750 -1.920212 -1.751477 -0.791121
## Dim. 2  1.230963  1.224334  1.977279  1.917537  1.838583  1.309298  1.085880
##              DKm1      DKm2      DKm3      DKm4      DKm5     DKm6      FIf1
## Mass     0.015228  0.012649  0.013386  0.015351  0.013017 0.014614  0.011544
## ChiDist  0.347520  0.944015  0.746858  0.577246  0.425435 0.305128  0.501340
## Inertia  0.001839  0.011272  0.007467  0.005115  0.002356 0.001361  0.002901
## Dim. 1  -0.766023 -2.082325 -1.692619 -1.241148 -0.652736 0.206674 -0.970679
## Dim. 2   0.508647  1.430786  0.679314  0.861313  0.985212 0.805173 -1.364560
##              FIf2      FIf3      FIf4      FIf5      FIf6      FIm1      FIm2
## Mass     0.011666  0.011544  0.014491  0.017438  0.011175  0.007123  0.008719
## ChiDist  0.766236  0.551096  0.495644  0.338299  0.414096  0.411753  0.655833
## Inertia  0.006850  0.003506  0.003560  0.001996  0.001916  0.001208  0.003750
## Dim. 1  -1.696716 -0.984276 -0.924988 -0.557306  0.352194 -0.266716 -1.390905
## Dim. 2  -0.559707 -1.756948 -1.483475 -1.152838 -1.760989 -1.762100 -1.272164
##              FIm3      FIm4      FIm5      FIm6     HUf1      HUf2     HUf3
## Mass     0.008719  0.012895  0.011789  0.009210 0.006631  0.010561 0.011666
## ChiDist  0.435509  0.346131  0.408938  0.420689 0.596829  0.528993 0.632471
## Inertia  0.001654  0.001545  0.001972  0.001630 0.002362  0.002955 0.004667
## Dim. 1  -0.803330  0.044427  0.510847  0.780773 1.159811  1.018217 1.125535
## Dim. 2  -1.344478 -1.605387 -1.387245 -1.118123 0.474792 -0.177617 1.513996
##             HUf4     HUf5     HUf6     HUm1      HUm2     HUm3     HUm4
## Mass    0.011175 0.011544 0.012772 0.006017  0.009210 0.012649 0.009824
## ChiDist 0.654467 0.546586 0.835835 0.487239  0.557409 0.492095 0.513571
## Inertia 0.004787 0.003449 0.008923 0.001429  0.002862 0.003063 0.002591
## Dim. 1  1.142602 1.103056 1.481505 0.991480  0.799636 1.025502 1.088005
## Dim. 2  1.501687 0.864556 1.274631 1.019905 -0.011945 0.980496 1.073058
##             HUm5     HUm6
## Mass    0.012526 0.007860
## ChiDist 0.499875 0.710900
## Inertia 0.003130 0.003972
## Dim. 1  1.097228 1.202188
## Dim. 2  0.572470 1.601967
## 
## 
##  Columns:
##                S        s         ?         e         E
## Mass    0.099472 0.237627  0.167874  0.260960  0.234066
## ChiDist 0.641178 0.439383  0.388506  0.322679  0.727480
## Inertia 0.040894 0.045876  0.025338  0.027172  0.123874
## Dim. 1  1.045509 0.846873  0.660109 -0.105643 -1.659727
## Dim. 2  1.310121 0.516896 -0.057407 -1.573335  0.713757</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="yhteisvaikutusmuuttujat.html#cb9-1"></a><span class="kw">summary</span>(maagaCA1)</span></code></pre></div>
<pre><code>## 
## Principal inertias (eigenvalues):
## 
##  dim    value      %   cum%   scree plot               
##  1      0.184895  70.3  70.3  ******************       
##  2      0.038751  14.7  85.0  ****                     
##  3      0.024006   9.1  94.1  **                       
##  4      0.015502   5.9 100.0  *                        
##         -------- -----                                 
##  Total: 0.263154 100.0                                 
## 
## 
## Rows:
##      name   mass  qlt  inr    k=1 cor ctr    k=2 cor ctr  
## 1  | BEf1 |   14  678    9 |  -83  43   1 | -320 635  38 |
## 2  | BEf2 |   24  914   11 | -278 650  10 | -177 264  20 |
## 3  | BEf3 |   21  320    3 |  -62  96   0 |  -95 224   5 |
## 4  | BEf4 |   24  164    3 |  -50  92   0 |  -44  71   1 |
## 5  | BEf5 |   23  332    5 |  133 304   2 |  -40  28   1 |
## 6  | BEf6 |   23  832   17 |  371 710  17 |  153 121  14 |
## 7  | BEm1 |   11  429    9 |  284 367   5 | -117  62   4 |
## 8  | BEm2 |   17  372    5 | -113 169   1 | -125 203   7 |
## 9  | BEm3 |   20  108    1 |   17  29   0 |  -29  79   0 |
## 10 | BEm4 |   22  966    5 |  225 812   6 |  -98 154   5 |
## 11 | BEm5 |   22  728    8 |  255 686   8 |  -63  42   2 |
## 12 | BEm6 |   26  788   15 |  348 788  17 |   -5   0   0 |
## 13 | BGf1 |    5  531   11 |  547 531   8 |   -9   0   0 |
## 14 | BGf2 |    8  860   14 |  640 853  17 |   59   7   1 |
## 15 | BGf3 |   12  815   21 |  617 804  24 |   75  12   2 |
## 16 | BGf4 |   10  932   12 |  519 927  15 |  -39   5   0 |
## 17 | BGf5 |   14  880   23 |  609 870  28 |   66  10   2 |
## 18 | BGf6 |   18  921   32 |  627 846  39 |  186  74  16 |
## 19 | BGm1 |    5  940    7 |  596 878   9 |  159  62   3 |
## 20 | BGm2 |    6  830    9 |  557 788  11 | -130  43   3 |
## 21 | BGm3 |    8  709   19 |  655 698  19 |   83  11   1 |
## 22 | BGm4 |    8  771   11 |  540 754  12 |  -81  17   1 |
## 23 | BGm5 |   10  979   11 |  524 977  15 |   21   2   0 |
## 24 | BGm6 |    9  692   27 |  701 647  24 |  184  45   8 |
## 25 | DEf1 |   13  425    3 |  -41  29   0 | -149 395   7 |
## 26 | DEf2 |   15  938   10 | -415 919  14 |  -60  19   1 |
## 27 | DEf3 |   19  846   13 | -333 582  11 | -224 264  24 |
## 28 | DEf4 |   23  985   13 | -390 982  19 |  -18   2   0 |
## 29 | DEf5 |   17  839    7 | -297 772   8 |  -87  67   3 |
## 30 | DEf6 |   23  116    8 |  -56  32   0 |   90  84   5 |
## 31 | DEm1 |   13  912    4 |  124 180   1 | -250 732  20 |
## 32 | DEm2 |   13  766    4 |   38  16   0 | -259 749  22 |
## 33 | DEm3 |   15  737    4 |  -64  63   0 | -210 674  17 |
## 34 | DEm4 |   21  137    5 |   -1   0   0 |  -89 137   4 |
## 35 | DEm5 |   19  603    5 |   76  75   1 | -202 529  20 |
## 36 | DEm6 |   22  849   12 |  244 427   7 |  242 422  34 |
## 37 | DKf1 |   10  991   15 | -567 839  18 |  241 152  15 |
## 38 | DKf2 |   14  991   49 | -888 831  58 |  389 160  53 |
## 39 | DKf3 |   17  963   53 | -816 793  60 |  377 170  61 |
## 40 | DKf4 |   18  977   57 | -826 820  66 |  362 157  61 |
## 41 | DKf5 |   16  998   38 | -753 894  48 |  258 105  27 |
## 42 | DKf6 |   12  808    9 | -340 579   8 |  214 229  14 |
## 43 | DKm1 |   15  981    7 | -329 898   9 |  100  83   4 |
## 44 | DKm2 |   13  989   43 | -895 900  55 |  282  89  26 |
## 45 | DKm3 |   13  982   28 | -728 950  38 |  134  32   6 |
## 46 | DKm4 |   15  941   19 | -534 855  24 |  170  86  11 |
## 47 | DKm5 |   13  643    9 | -281 435   6 |  194 208  13 |
## 48 | DKm6 |   15  355    5 |   89  85   1 |  158 270   9 |
## 49 | FIf1 |   12  980   11 | -417 693  11 | -269 287  21 |
## 50 | FIf2 |   12  927   26 | -730 907  34 | -110  21   4 |
## 51 | FIf3 |   12  984   13 | -423 590  11 | -346 394  36 |
## 52 | FIf4 |   14  991   14 | -398 644  12 | -292 347  32 |
## 53 | FIf5 |   17  952    8 | -240 502   5 | -227 450  23 |
## 54 | FIf6 |   11  835    7 |  151 134   1 | -347 701  35 |
## 55 | FIm1 |    7  787    5 | -115  78   1 | -347 710  22 |
## 56 | FIm2 |    9  977   14 | -598 832  17 | -250 146  14 |
## 57 | FIm3 |    9  998    6 | -345 629   6 | -265 369  16 |
## 58 | FIm4 |   13  837    6 |   19   3   0 | -316 834  33 |
## 59 | FIm5 |   12  734    7 |  220 289   3 | -273 446  23 |
## 60 | FIm6 |    9  911    6 |  336 637   6 | -220 274  12 |
## 61 | HUf1 |    7  723    9 |  499 698   9 |   93  25   1 |
## 62 | HUf2 |   11  689   11 |  438 685  11 |  -35   4   0 |
## 63 | HUf3 |   12  808   18 |  484 586  15 |  298 222  27 |
## 64 | HUf4 |   11  768   18 |  491 564  15 |  296 204  25 |
## 65 | HUf5 |   12  850   13 |  474 753  14 |  170  97   9 |
## 66 | HUf6 |   13  671   34 |  637 581  28 |  251  90  21 |
## 67 | HUm1 |    6  935    5 |  426 766   6 |  201 170   6 |
## 68 | HUm2 |    9  381   11 |  344 381   6 |   -2   0   0 |
## 69 | HUm3 |   13  957   12 |  441 803  13 |  193 154  12 |
## 70 | HUm4 |   10  999   10 |  468 830  12 |  211 169  11 |
## 71 | HUm5 |   13  942   12 |  472 891  15 |  113  51   4 |
## 72 | HUm6 |    8  726   15 |  517 529  11 |  315 197  20 |
## 
## Columns:
##     name   mass  qlt  inr    k=1 cor ctr    k=2 cor ctr  
## 1 |    S |   99  653  155 |  450 492 109 |  258 162 171 |
## 2 |    s |  238  741  174 |  364 687 170 |  102  54  63 |
## 3 |      |  168  535   96 |  284 534  73 |  -11   1   1 |
## 4 |    e |  261  941  103 |  -45  20   3 | -310 921 646 |
## 5 |    E |  234 1000  471 | -714 962 645 |  141  37 119 |</code></pre>
</div>
<div id="stabiilisuus" class="section level2">
<h2><span class="header-section-number">5.3</span> Stabiilisuus</h2>
<p><strong>k</strong> Stabiilius - teorialiitteessä laajemmin mutta tässä lyhyt vilkaisu.
Taulukko alkaa harveta, edellä kerrottiin että aineisto painottuu kaikissa maissa
vanhempiin ikäluokkiin.</p>
<p><strong>yksinkertainen tarkistus?</strong> Löytyykö riviproviileja joilla pieni massa ja suuri
kontribuutio? Ei löydy (Galkussa tuloksia), mutta jo kuvan tukkoisuus vaatii
luokkien yhdistelyä. Aika työlästä!</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="täydentävät-pisteet.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="osajoukon-korrespondenssianalyysi.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["JH_capaper.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
